### ISSUE TITLE
modded compatibility and modpack configuration

### ISSUE THREAD

**Issue by AlleCraft-alterego** [stfwi/anthillinside#1]
can be add 0 value for drop ant hive from redstone ore ?

can be added a config for add/remove upgrades blocks for exemple for add modded crafting table, modded hopper or modded stonecutter......  or can be added a tag for any upgrades blocks for exemple "anthillinside:craftingtable" well... any block/item with this tag open crafting table gui in ant hive

**Comment by stfwi** [comment]
Salute Alle, aye the setting for drop probability=0 can be added easily. The tool control config is also doable, I just need to double check if tagging (I normally use tags for similar things) is appropriate here, or if a conventional config is better. Tendency is to use the conventional config because tags may overlay due to implicit extending of other mods, and cause undefined behaviour what the hive should do. Cheers,-

**Comment by AlleCraft-alterego** [comment]
Thanks, for drop value can be added in the description config the ppossibility to add 0 value ? (For now there is write only from 1 to 20)

**Comment by AlleCraft-alterego** [comment]
And..... Can be add stonecutter on hive ? With a whitelist slot and stone cutter gui ( whitelist slot for click and lock stonecutter recipe )

**Comment by stfwi** [comment]
Hi, not sure yet - maybe'ish ...

I did implement a config today and made a brief testing - but unfortunately I'm out of time for this week. 

If you like you can check this mod version (1.2.15 alpha1). In the config you now can:
- set the drop probability to 0 (OFF, no drops from Redstone mining),
- configure the allowed items for crafting, smelting, etc.

The `anthillinside-common.toml` has automatically the new entries with defaults:

```toml

#Settings affecting the logical server side.
[server]
 [server.tweaks]

  #Sets how probable it is that a Red Ant Hive drops when manually mining Redstone Ore. The value 0 disables drops from Redstone mining (you need to add your own recipe in a data pack).
  #Range: 0 ~ 20
  hive_drop_chance_percent = 3   # -----------> CAN BE SET TO 0


#Settings where you can explicitly define which tools or other control items the Hive knows.
[hive_control_items]
 #Items that can be placed into the Hive control slot to activate ~normal crafting~.
 crafting_tables = ["minecraft:crafting_table"]
 #Items that can be placed into the Hive control slot to activate ~smelting or cooking~.
 furnaces = ["minecraft:furnace"]
 #Items that can be placed into the Hive control slot to activate ~fast smelting~.
 blast_furnaces = ["minecraft:blast_furnace"]
 #Items that can be placed into the Hive control slot to activate ~fast cooking~.
 smokers = ["minecraft:smoker"]
 #Items that can be placed into the Hive control slot to activate ~composting~.
 composters = ["minecraft:composter"]
 #Items that can be placed into the Hive control slot to activate ~potion brewing~.
 brewing_stands = ["minecraft:brewing_stand"]
 #Items that can be placed into the Hive control slot to activate ~disenchanting~.
 grindstones = ["minecraft:grindstone"]
 #Items that can be placed into Hive slots to activate ~item pass through (control slot), item input drawing, and item output inserting~.
 hoppers = ["minecraft:hopper"]
 #Items that can be placed into the Hive output slot to activate ~item drop output (soft eject)~.
 droppers = ["minecraft:dropper"]
 #Items that can be placed into the Hive output slot to activate ~item dispense output (fast eject)~.
 dispensers = ["minecraft:dispenser"]
 #Items that can be placed into the Hive control slot to activate ~animal or plant shearing~.
 shears = ["minecraft:shears"]
 #Items that can be placed into the Hive control slot to activate ~farmning~.
 hoes = ["minecraft:iron_hoe", "minecraft:diamond_hoe", "minecraft:netherite_hoe"]
 #Items that can be placed into the Hive control slot to activate ~tree chopping~.
 axes = ["minecraft:iron_axe", "minecraft:diamond_axe", "minecraft:netherite_axe"]
 #Items that can be placed into the Hive control slot to activate ~block breaking~.
 pickaxes = ["minecraft:iron_pickaxe", "minecraft:diamond_pickaxe", "minecraft:netherite_pickaxe"]

```

If it is already good I can make a release from that next weekend and push it to curse etc. Cheers,-
